version: '3'

services:
  notWorkingMySql8:
    image: mysql:8.0.25
    ports:
      - "8306:3306"
    command: --explicit-defaults-for-timestamp=OFF --default-authentication-plugin=mysql_native_password --init-file /data/init.sql
    volumes:
      - ./init.sql:/data/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root

  workingMySql5:
    image: mysql:5.7
    ports:
      - "5306:3306"
    command: --init-file /data/init.sql
    volumes:
      - ./init.sql:/data/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
